name : Triggers
run-name: Triggers Runs ¡Aprendiendo a usar Trigeers!
on: [push]
jobs:
  hola-mundo_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run : echo 'hola mundo'
      - name : echo_2
        run : echo 'okoko' 
